function data = get_data_tex(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESPHIITERATION110 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RESPHIITERATION110 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  resphiiteration110 = importfile("C:\Users\yigit\Desktop\ION_MOTOR\[res]phi-iteration110.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jan-2022 02:08:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

%% Convert to output type
data = table2array(data);

end